---
- hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: enable vi mode to vagrant user
      lineinfile:
        path: /home/vagrant/.bashrc
        line: set -o vi

    - name: install python3, docker-engine, git
      yum:
        name:
          - python3
          - pip3
          - docker-engine
          - git
        state: present

    - name: create docker group
      group:
        name: docker

    - name: add vagrant user to docker group
      user:
        groups: docker
        append: yes
        name: vagrant

    - name: enable docker daemon
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: clone aws-boto3-docker repo
      git:
        repo: 'https://github.com/joshRooz/AWS-Boto3-Docker.git'
        dest: /home/vagrant/aws-boto3-docker

    - name: configure git email and user info
      command: git config --global user.email "54345520+joshRooz@users.noreply.github.com"
    - command: git config --global user.name "Josh Roose"
