#!/bin/bash
echo "Collecting latest build's version matrix!"
boto3=$(docker run --rm joshrooz/aws-boto3-sdk  pip show boto3 | grep Version | awk -F\   '{print $NF}')
python=$(docker run --rm joshrooz/aws-boto3-sdk python --version | awk -F\  '{print $NF}')

echo "boto3: ${boto3}"
echo "python: ${python}"
