#!/bin/bash
echo "Collecting latest build's version matrix!"
boto3=$(docker run --rm joshrooz/aws-boto3-sdk  pip show boto3 | grep Version | awk -F\   '{print $NF}')
python=$(docker run --rm joshrooz/aws-boto3-sdk python --version | awk -F\  '{print $NF}')

echo "boto3: $boto3"
echo "python: $python"

curl -v \
  -X POST \
  -H "Accept: application/vnd.github.v3+json" \
  -H "Authorization: token $GITHUB_REPO_TOKEN" \
  https://api.github.com/repos/joshrooz/aws-boto3-docker/dispatches \
  -d "{\"event_type\":\"post-push\", \"client_payload\": { \"boto3-version\": \"$boto3\", \"python-version\": \"$python\" } }"
