#!/bin/bash
echo "Collecting latest build's version matrix!"
boto3=$(docker run --rm joshrooz/aws-boto3-sdk  pip show boto3 | grep Version | awk -F\   '{print $NF}')
python=$(docker run --rm joshrooz/aws-boto3-sdk python --version | awk -F\  '{print $NF}')

echo "boto3: $boto3"
echo "python: $python"

GITHUB_TOKEN=0e356f1c83c23d921f903701f741273693957d7b
echo "Token: $GITHUB_TOKEN"

curl \
  -X POST \
  -H "Accept: application/vnd.github.v3+json" \
  -H "Authorization: token $GITHUB_TOKEN" \
  https://api.github.com/repos/joshrooz/aws-boto3-docker/dispatches \
  -d '{"event_type":"post-push", "client_payload": { "boto3": "$boto3", "python": "$python" } }'
